export const LOGIN_USER = 'LOGIN_USER';

export const GET_ALL_USERS_START   =  'GET_ALL_USERS_START';
export const GET_ALL_USERS_SUCCESS =  'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAIL    =  'GET_ALL_USERS_FAIL';
