export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const AUTO_LOGIN = 'AUTO_LOGIN';

export const GET_ALL_USERS_START   =  'GET_ALL_USERS_START';
export const GET_ALL_USERS_SUCCESS =  'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAIL    =  'GET_ALL_USERS_FAIL';


export const SET_ALL_USERS_QUESTIONS_START =    'SET_ALL_USERS_QUESTIONS_START';
export const SET_ALL_USERS_QUESTIONS_SUCCESS =  'SET_ALL_USERS_QUESTIONS_SUCCESS';
export const SET_ALL_USERS_QUESTIONS_FAIL =     'SET_ALL_USERS_QUESTIONS_FAIL';

export const SAVE_QUESTION_ANSWER_START = 'SAVE_QUESTION_ANSWER_START';
export const SAVE_QUESTION_ANSWER_SUCCESS = 'SAVE_QUESTION_ANSWER_SUCCESS';
export const SAVE_QUESTION_ANSWER_FAIL = 'SAVE_QUESTION_ANSWER_FAIL';

export const ADD_QUESTION_START = 'ADD_QUESTION_START';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const ADD_QUESTION_FAIL = 'ADD_QUESTION_FAIL';