export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_ALL_USERS_START   =  'GET_ALL_USERS_START';
export const GET_ALL_USERS_SUCCESS =  'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAIL    =  'GET_ALL_USERS_FAIL';


export const SET_ALL_USERS_QUESTIONS_START =    'SET_ALL_USERS_QUESTIONS_START';
export const SET_ALL_USERS_QUESTIONS_SUCCESS =  'SET_ALL_USERS_QUESTIONS_SUCCESS';
export const SET_ALL_USERS_QUESTIONS_FAIL =     'SET_ALL_USERS_QUESTIONS_FAIL';
